language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
  - rust: nightly
env:
  global:
    secure: T539XLLi1Z+BBwnwqm/AnHJjNY/YUX4rRkEr1Nt5u/KKhQePjXEjGjqOC9/aVYbAKEc4bmTZkRrt6KoLRKhUOqHAAI/4xZkkey6vehqAclWX+rtOlbX0qJFFI/v2YHzYEU+32afhcXI+d1ttcu3ai8S92VPTt4jcT3dhxvBQAzzizzNsndLbbVJo8AGSnI0hV5vz/jOjtrEcFCrqjBuejZjZDFOZ9Jkg3VtITvR8QyCTlRE5zKNGDjj3Iaw/XVwUg1GqVqfyeS3WyQ5HjqtQbLm6/iA7zH3ISaQ5dAafzCKhB0bErWvUgk47N4Btku0tL9M0StFYBJQWzGkj/IENfNW1WlAjoaO4i75HO5Ms53QZipFPKBlQgz1iqKbETfJ0B2LZvXbnRkVNLrbIs2OE8oG/7mq0kp44qOPkWKjJEtAjCn0wgEyqMKrdJ09V8OzzpMvLnzdW4zG+Wuqm4tBuVHErCw47WFSncL3ibOwqS6qEhqbf6+uhs/j0Mmqrr3HRQJZGT6VSmMx1LUB/oMK6QseVTKgUp5AOUTmpUc3Pe8tNjAy9uvzy0aUEkZP3MRmYE0QPUqanvlTX2sO2EKBKfvNMgaBR37ZyQjjTXtPCvvneMP5VIBk6mfSoIVmXQB1e/sRN1rPvYCfDUWL+u2TDM6hHseAa6HwfUe5RTS2BCVk=
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --no-run --verbose
  - travis-cargo --only stable doc
after_success:
  - travis-cargo --only stable doc-upload
cache:
  pip: true
  cargo: true