[package]
name = "ropey"
version = "0.4.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]

[dependencies]
arrayvec = "0.4"
smallvec = "0.5"
unicode-segmentation = "1.2"

[dev-dependencies]
rand = "0.3"