[package]
name = "ropey"
version = "0.8.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
description = "An efficient and robust editable text buffer for Rust"
documentation = "https://docs.rs/ropey"
repository = "https://github.com/cessen/ropey"
readme = "README.md"
license = "MIT"
keywords = ["rope", "text", "edit", "buffer"]
categories = ["text-processing", "data-structures"]

[badges]
travis-ci = { repository = "cessen/ropey" }

[dependencies]
smallvec = "0.6"

[dev-dependencies]
rand = "0.5"
proptest = "0.8"
bencher = "0.1.5"
unicode-segmentation = "1.2.1"

#-----------------------------------------

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "remove"
harness = false

[[bench]]
name = "from_str"
harness = false

[[bench]]
name = "queries"
harness = false