[package]
name = "ropey"
version = "0.5.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
description = "Efficient utf8 text buffer for Rust"
documentation = "https://docs.rs/ropey"
repository = "https://github.com/cessen/ropey"
readme = "README.md"
license = "MIT"
keywords = ["rope", "text", "buffer"]

[dependencies]
smallvec = "0.6"
unicode-segmentation = "1.2"

[dev-dependencies]
rand = "0.3"