[package]
name = "ropey"
version = "1.3.2"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
description = "A fast and robust text rope for Rust"
documentation = "https://docs.rs/ropey"
repository = "https://github.com/cessen/ropey"
readme = "README.md"
license = "MIT"
keywords = ["rope", "text", "edit", "buffer"]
categories = ["text-processing", "data-structures"]
exclude = ["/design/*", "/benches/*.txt", "/fuzz/**", "/.github/*"]

[badges]
travis-ci = { repository = "cessen/ropey" }

[dependencies]
smallvec = "1.0.0"
str_indices = "0.3.0"

[dev-dependencies]
rand = "0.8"
proptest = "1.0"
criterion = { version = "0.3", features = ["html_reports"] }
unicode-segmentation = "1.3"

#-----------------------------------------

[[bench]]
name = "create"
harness = false

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "remove"
harness = false

[[bench]]
name = "queries"
harness = false

[[bench]]
name = "iterators"
harness = false
