[package]
name = "ropey"
version = "0.5.5"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
description = "An efficient text buffer for Rust"
documentation = "https://docs.rs/ropey"
repository = "https://github.com/cessen/ropey"
readme = "README.md"
license = "MIT"
keywords = ["rope", "text", "buffer"]
categories = ["text-processing", "data-structures"]

[badges]
travis-ci = { repository = "cessen/ropey" }

[dependencies]
smallvec = "0.6"
unicode-segmentation = "1.2"

[dev-dependencies]
rand = "0.3"
quickcheck = "0.5"
bencher = "0.1.4"

#-----------------------------------------

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "remove"
harness = false

[[bench]]
name = "from_str"
harness = false

[[bench]]
name = "queries"
harness = false