name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Every-other month, to make sure new Rust
    # releases don't break things.
    - cron: '15 12 5 1,3,5,7,9,11 *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-stable:
    name: Build and test, Rust-nightly
    runs-on: ubuntu-latest
    steps:
      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      # Build and test
      - run: cargo +nightly build
      - run: cargo +nightly test

  run-miri:
    name: Run Miri
    runs-on: ubuntu-latest
    steps:
      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: miri

      # Build and test
      # --no-default-features to get rid of the simd feature
      - run: cargo miri test
        env:
          MIRIFLAGS: "-Zmiri-strict-provenance"

  clippy-check:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    

